version: "3.7"
services:
  app:
    build:
      args:
        user: square_user
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: square_app
    #container_name: travellist-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - square_app_network
  square_db:
    image: mysql:5.7
    container_name: square_db
    restart: unless-stopped
    ports:
      - 3310:3306
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - square_app_network
  php-queue:
    restart: unless-stopped
    image: square_app
    container_name: square_php_queue
    command: php artisan queue:work
    volumes:
      - ./:/var/www
    networks:
     - square_app_network
  nginx:
    image: nginx:1.17-alpine
    container_name: square_nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d
    networks:
      - square_app_network
volumes:
  dbdata:
    driver: local
networks:
  square_app_network:
    driver: bridge
